##########################################################################################
# _config.yml - Pages configuration file                                                 #
#                                                                                        #
# Author: Ben Winchester                                                                 #
# Date created: 14/04/2023                                                               #
# License: MIT                                                                           #
#                                                                                        #
##########################################################################################

title: BenWinchester
description: A GitHub page containing information on my Github projects and research.
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
