##########################################################################################
# _config.yml - Pages configuration file                                                 #
#                                                                                        #
# Author: Ben Winchester                                                                 #
# Date created: 14/04/2023                                                               #
# License: MIT                                                                           #
#                                                                                        #
##########################################################################################

theme: minimal
